train: C:/Users/mrben/Desktop/Projects/Hawkatuans/AIC-GM-Comp2025/data/train/images  ## REPLACE WITH YOUR PATH
val: C:/Users/mrben/Desktop/Projects/Hawkatuans/AIC-GM-Comp2025/data/val/images  ## REPLACE WITH YOUR PATH

names:
  0: person
  1: car
  2: bike
